name = "JulCom"
uuid = "f486e128-f336-4294-9258-09db02fae8aa"
authors = ["Benjamin Vittrant"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
